### ISSUE TITLE
Could not access location \Microsoft\VisualStudio\9.0\Addins

### ISSUE THREAD

**Issue by jimgust** [TaoK/PoorMansTSqlFormatter#110]
I tried to install with the "Also install for Visual Studio" unchecked.  After I click next I'm getting an error "Could not access location \Microsoft\VisualStudio\9.0\Addins".  At this point the installer goes into a loop and I'm forced to cancel.

I'm on a Win7 64bit machine.
I do have VSTA 9 installed in "C:\Program Files (x86)\Microsoft Visual Studio 9.0\".

**Comment by TaoK** [comment]
This may be addressed in the latest Add-In installer package (for these old SSMS versions) at http://architectshack.com/PoorMansTSqlFormatter.ashx. It's now using standard Wix setup configuration rather than the mysterious and horrible Visual Studio Setup Projects functionality.

Given the age of this issue, it seems unlikely the original issue reporter still cares, so I will close the issue. Let me know if it should be reopened!
