### ISSUE TITLE
No Spaces in exponential notation (for DB2)

### ISSUE THREAD

**Issue by dolonnen** [TaoK/PoorMansTSqlFormatter#142]
Hi and many thanks for your great Tool.

in IBM DB2 is no space in an e exponential notation allowed. For example "3.6E+03" could be changed to "3.6e+03" but **not** to "3.6e + 03" or to "3.6E + 03". This would make trouple to the DB2 guys.

Could you make the spaces optional or something?

**Comment by TaoK** [comment]
Hi @dolonnen, thanks for the details, it turns out what you are requesting is not specific to DB2 (if it were, I would have had to think about it a little bit), but actually corresponds to the way SQL Server (T-SQL) works also. "3.6e+03" should indeed never be interpreted as "6.6" but rather as "3600".

To address this, a new test case should be added in the simple type parsing test file at https://github.com/TaoK/PoorMansTSqlFormatter/blob/master/PoorMansTSqlFormatterTest/Data/InputSql/01_SimpleTypes_StrangeRules.txt (and its parsed and formatted variants), and handling added for this case in the tokenizer at https://github.com/TaoK/PoorMansTSqlFormatter/blob/master/PoorMansTSqlFormatterLib/Tokenizers/TSqlStandardTokenizer.cs 

I'm not going to make any predictions or promises as to when I might get to actually doing such a thing,  or even "accepting" a pull request (to my shame, there is a pretty-interesting pull request from 2014 pending), but I would certainly **like** to fix this...
