### ISSUE TITLE
Explain Identity (Mirror) Formatting

### ISSUE THREAD

**Issue by mika76** [TaoK/PoorMansTSqlFormatter#156]
There does not seem to be any info on what this option is...

**Comment by TaoK** [comment]
It's a bit silly, should maybe be hidden by default - it's a formatting option which is supposed to output the content in exactly the same format in which it was found. It's used in testing the library, to ensure that the parsing is completely non-destructive, retaining all the input content (including whitespace, comments, etc).

There is one context in which it can be useful, which is when you request *coloring only* - the "Identity Formatter" has the option to output the content with keyword coloring. When invoked, this option outputs HTML instead of simple text, with different CSS classes representing different types of text/tokens in the output.

**Comment by TaoK** [comment]
I've added a ///<summary> explanation in the class to this effect.
