### ISSUE TITLE
PoorMansTSqlFormatterNPPPlugin.dll is not compatible with the current version of Notepad++

### ISSUE THREAD

**Issue by jschof** [TaoK/PoorMansTSqlFormatter#157]
Running Notepad++ v7.4.1 (32-bit), trying to use SqlFormatterNppPlugin.1.5.1.

This message appears both when installed through Plugin Manager and when installed manually.

Please advise. I would prefer to stay with current version of NPP if possible.

Thanks!

**Comment by manoharreddyporeddy** [comment]
i was trying poor mans on notepad++ yesterday
i was able to install successfully, see this for help: https://stackoverflow.com/questions/3310188/what-free-sql-formatting-tools-exist#comment75607875_6745589

**Comment by jschof** [comment]
Thanks but I don't have a problem installing the plugin. After NPP restarts is when I get the error message.

![image](https://cloud.githubusercontent.com/assets/15448821/26753611/023fb7b6-4838-11e7-8c64-5ec295b39d58.png)

Are you running the latest version?

**Comment by manoharreddyporeddy** [comment]
I had another problem.
1. I have uninstalled the existing one.
2. installed the 32 bit version: using the link https://stackoverflow.com/questions/3310188/what-free-sql-formatting-tools-exist#comment75607875_6745589
3. AGAIN installed the 32 bit version using above line
4. only then the I could see options.

Also, I have done the above procedure on multiple machines now
following the above
solved the issue.

**Comment by TaoK** [comment]
Hi, unfortunately the message you showed in the screenshot above is very generic - it really doesn't say anything about what the problem is.

I'd like to do something cleverer about catching and handling errors at the plugin-loading stage, I have to admit I haven't worried about it much in the past because, well, it effectively always worked... The few errors I've heard about over the years have almost always been down to someone trying to install the plugin manually (as opposed to through plugin manager) and missing some of the files or putting them in the wrong place.

There are only two possibilities that jump to mind for the error you are getting:

1. I've had intermittent reports that .Net 2.0 might is not installed on some Windows 10 machines, and that might be a good reason for the plugin not to work. Can you confirm whether:
    - You're running windows 10 or some other OS, and
    - Whether you have .Net 2.0 installed (eg following the instructions at https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx#net_a )
2. There could be some other completely unrelated environment-specific issue (permissions issues related to unusual user profile location settings, disk space issues, etc) - can you confirm whether this is a reasonably "normal" personal computer, or whether it's a managed corporate computer?

**Comment by TaoK** [comment]
(just for the record, I just updated to Notepad++ 7.4.1, updated to the latest plugin manager as recommended, and then installed the Poor Man's T-SQL Formatter plugin through the plugin manager - without issues - on my new Windows 10 personal laptop)

**Comment by jschof** [comment]
Damn you're good Tao! 

Using the link you provided I established that I had the following installed:

**Version:** .NET Framework 4.5.2
**Value of the Release DWORD:** 379893

Should be fine, right? But in looking at the registry I noticed that the installation path seemed to indicate it was the 64-bit version of .NET:

> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

I tried installing the 32-bit version of .NET 2.0 from [Microsoft's web site](https://www.microsoft.com/en-ca/download/confirmation.aspx?id=16614)  but it actually ended up installing .NET 3.5 (includes .NET 2.0 and 3.0). 

Installed the plugin again using the plugin manager, re-started NPP and BAM, everything is hunky dory. 

Thanks for your help (and the plug-in)!!!
 
 
BTW Using NPP on USB key in personal desktop running latest version of Windows 10.

**Comment by TaoK** [comment]
Great, glad you're sorted, @jschof !

For future reference (on this thread), it appears that in Windows 10 the .Net Framework 3.5 SP1 (including .Net 2.0, and so enabling the NPP plugin) is an **optional feature** of windows, that can be enabled in the "**Turn Windows features on or off**" screen/functionality. It's called ".NET Framework 3.5 (includes .NET 2.0 and 3.0)", and it's right at the top of the list of optional features.

For now, I don't think it's warranted to release a whole separate NPP plugin targeting a later .Net framework, but if anyone disagrees please follow up on this thread!

**Comment by TaoK** [comment]
Chiel Borkent mentions he cannot install .Net 2.0 (3.5) on his Windows 10 environment - I'm hoping for more information as to why that is.

**Comment by jschof** [comment]
I only noticed after I installed it that I might have also been able to do so through the method you mentioned. Perhaps he try to installing it using the link I provided / used?

[https://www.microsoft.com/en-ca/download/confirmation.aspx?id=16614](url)
