### ISSUE TITLE
The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

### ISSUE THREAD

**Issue by HeinziAT** [TaoK/PoorMansTSqlFormatter#168]
First, let me thank you for making your tool available for recent versions of SSMS!

Repro:
1. Download and install current version SSMS (17.3).
2. Download and install PoorMansTSqlFormatter (1.6.1).
3. Start SSMS, create new query window, enter "SELECT * FROM mytable" (without the quotes).
4. Choose Tools/Format T-SQL Code.

Expected result: The SQL statement is formatted.
Actual result: The SQL statement is formatted and a message box with the following text appears:

> The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

**Comment by TaoK** [comment]
Congratulations! I've seen this issue occasionally for years, but you're the first to report it (in fact, I now realize I didn't create an issue either). 

It happens when you request to format a document that has only one line. I assume I'm doing something silly like trying to put the cursor on line -1 or something.

For now, please ignore (the error is harmless, and any non-trivial sql formats to multiple lines anyway, so any subsequent reformat will no longer see this error). I'll see about fixing it sometime soon.

**Comment by HeinziAT** [comment]
Thanks for the fast answer!

Your explanation makes perfect sense, and I probably only stumbled upon the error because I was testing SSMS 17 support with a toy example with only one line.

Take your time. Since the workaround you provided is really simple (just add a second line or ignore the message), I don't need a fix anytime soon.

**Comment by sl-eal** [comment]
The issue happens for me too, regardless of the number of lines in the query.  However it only seems to occur when my cursor is on the very last character on the last line of the query.

**Comment by danblank000** [comment]
I find that if you highlight the text before applying the format then it works with no error

**Comment by TaoK** [comment]
I think I finally have it: the error happens when:

* there is no empty last line in the sql window (the last line has content), AND
* the cursor is on the last line

After a successful format, an empty last line is added, and therefore the error does not come back for that SQL even if you move the cursor anywhere.

**Comment by TaoK** [comment]
Addressed in version 1.6.6 (VS & SSMS add-in and extension), downloadable in the usual places.
