### ISSUE TITLE
FormatterPackage fails to load in SSMS 17.3

### ISSUE THREAD

**Issue by mrkaminski77** [TaoK/PoorMansTSqlFormatter#187]
Trying to install for SSMS 17.3 on Server 2012. It is a terminal server and after setting to install mode and installing the plugin we get this error.

![image](https://user-images.githubusercontent.com/28722245/33156241-e86abae2-d04b-11e7-803a-9f90434da460.png)

In the activitylog.xml I can see the following entry:
```
  <entry>
    <record>35</record>
    <time>2017/11/23 01:28:45.005</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Appid denied the loading of package</description>
    <guid>{247609B1-2692-47D6-972A-976544685F0E}</guid>
  </entry>
```
Is there some workaround for this? We have tried uninstall, re-install and reboot.

**Comment by Langthjem** [comment]
Also happening with SSMS 17.3 on Windows 10 Pro (x64).

**Comment by TaoK** [comment]
Hi guys, I think I need a little more information here to understand what's going on.

First of all (to both of you), **what happens if you say "No" and restart SSMS?** My expectation is that **SSMS loads without errors the second time**, and the extension is loaded and working. 

If this is true, then the explanation is that at first load of SSMS, a registry key that the installer was supposed to add (in the Hkey_Current_User / HKCU area of the registry) was not there.

I imagine there are all sorts of possible ways this can happen, but for @mrkaminski77 the mention of "terminal server" makes me think there is probably something interesting happening with multiple users (the user who installs is not the same one that logs in, or the user's registry changes are cleared at login or logout, or something interesting like that).

For @Langthjem I'm afraid I don't have any obvious theories - regular users who've seen this behavior in the past are those that used the Visual Studio VSIX package to install to SSMS, but since the 21st of November they're completely separate VSIX packages to completely prevent this issue. Is it possible you installed the Visual Studio VSIX package from before the 21st?

For background, the reason you see this message if a specific registry key is not explicitly added, is that SSMS doesn't actually officially support extensions. If you click "No" in the dialog presented, SSMS itself actually puts a "noload" registry entry in place, and that same entry allows the extension to load successfully the next time around. Crazy stuff. Even more crazy is that as the extension loads, SSMS actually **removes** this registry key, so the extension code needs to add it back (so that the extension can load successfully on the **following** load of SSMS).

This crazy "add weird registry entries and add them back when SSMS deletes them" flow is one that every SSMS extension needs to implement, even the commercial ones as far as I know.

If there's something else going on, let's find out what it is! Given the timing of your issues, it seems "not too unlikely" that I messed up the splitting of the single VSIX package into the two separate ones on Nov 21st...

**Comment by TaoK** [comment]
Don't bother reading all that text - I messed up the installer during the split at the start of the week.

The problem will have been temporary (as long as you say "No" in the error  dialog, the extension loads fine on next SSMS restart and forever after), but still, almost 300 downloads of the bad installer... :(

Fixed installer is live, downloadable at http://architectshack.com/PoorMansTSqlFormatter.ashx

Sorry about the inconvenience.

**Comment by MikeOtown** [comment]
I resolved this error by renaming this folder...  C:\Users\mike\AppData\Local\Microsoft\SQL Server Management Studio\14.0\ComponentModelCache
