### ISSUE TITLE
Downloads via https

### ISSUE THREAD

**Issue by chcg** [TaoK/PoorMansTSqlFormatter#207]
@TaoK See https://github.com/bruderstein/npp-plugins-x64/issues/114. Could you provide a download location with https? E.g. https://github.com/TaoK/PoorMansTSqlFormatter/releases.

**Comment by TaoK** [comment]
As of today, the NPP plugins can be downloaded over HTTPS:

* https://github.com/TaoK/PoorMansTSqlFormatter/releases/download/1.6.10/SqlFormatterNppPlugin.1.6.10.b.zip
* https://github.com/TaoK/PoorMansTSqlFormatter/releases/download/1.6.10/SqlFormatterNppPlugin.x64.1.6.10.b.zip

(turns out I had to make a change for the new Plugin Admin system, and HTTPS support was an accidental benefit!)

**Comment by chcg** [comment]
@TaoK Thanks, download locations are now also changed for 32/64-bit PM lists.
