### ISSUE TITLE
Extension Not Loaded b/c of Deprecated Synchronous Autoload APIs

### ISSUE THREAD

**Issue by spottedmahn** [TaoK/PoorMansTSqlFormatter#229]
![image](https://user-images.githubusercontent.com/14079228/62069175-aedfe480-b205-11e9-86a7-31f32017df49.png)

[Convert an existing VSPackage to AsyncPackage](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2019#convert-an-existing-vspackage-to-asyncpackage)

[Synchronously autoloaded extensions](https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019)

Happy to take a stab at fixing it 😊

**Comment by TaoK** [comment]
This issue has been addressed, although it required a split of the extension - the existing extension supports VS2015, VS2017 and VS2019 moving forward, with an async loading approach. 

A new extension has been created to support VS2013 ~~and VS2015~~. Hopefully no-one needs it, but it's there in case anyone does.

Existing VS2015-2019 users will get upgraded according to their extension upgrade policy, and will stop getting performance warnings when they do.

Existing VS2013 users will not automatically get any further updates. For now that doesn't matter, because there are no changes that would impact these users. Moving forward they might need to install the new extension (and uninstall the old one) to get new enhancements.

New users of any version (VS2013-2019) should find only the version they need on the marketplace.

https://marketplace.visualstudio.com/items?itemName=TaoKlerks.PoorMansT-SqlFormatterSSMSVSExtension

https://marketplace.visualstudio.com/items?itemName=TaoKlerks.PoorMansT-SqlFormatterSSMSVSExtension2013

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/62297380-1c2a8a00-b43f-11e9-8592-582eab3a8cfd.png)
 on https://marketplace.visualstudio.com/items?itemName=TaoKlerks.PoorMansT-SqlFormatterSSMSVSExtension2015

**Comment by spottedmahn** [comment]
FYI

>AsyncPackage was introduced in VS2015

https://twitter.com/mkristensen/status/1156926338466320384?s=20

**Comment by spottedmahn** [comment]
just upgraded, no more warning, thanks!!

**Comment by TaoK** [comment]
> [404] on https://marketplace.visualstudio.com/items?itemName=TaoKlerks.PoorMansT-SqlFormatterSSMSVSExtension2015

Thanks, didn't remember there was a "make public" step, fixed!

> AsyncPackage was introduced in VS2015

Yes, but the async initialization stuff didn't work as easily in that version, so I cut off at 2017 :)

**Comment by spottedmahn** [comment]
>Yes, but the async initialization stuff didn't work as easily in that version, so I cut off at 2017 :)

Fair enough 😊

Thanks for creating this awesome tool and all your support 🤝

**Comment by TaoK** [comment]
Just to close out this comment thread, after @spottedmahn kindly put me in touch with the VS Extensibility guru @madskristensen on twitter, I was able to get VS2015 into the current supported extension, leaving only 2013 stranded. (Issue #236)
